version: '3.9'
services:
  app_prod1:
    build:
      context: backend/app
      dockerfile: backend/app/Dockerfile.prod
    container_name: app_prod1
    ports:
      - 8000:8080
    restart: on-failure
    volumes:
      - .:/backend/app
    depends_on:
      - postgresdb

  app_prod2:
    build:
      context: backend/app
      dockerfile: backend/app/Dockerfile.prod
    container_name: app_prod2
    ports:
      - 8001:8080
    restart: on-failure
    volumes:
      - .:/backend/app
    depends_on:
      - postgresdb

  app_prod3:
    build:
      context: backend/app
      dockerfile: backend/app/Dockerfile.prod
    container_name: app_prod3
    ports:
      - 8002:8080
    restart: on-failure
    volumes:
      - .:/backend/app
    depends_on:
      - postgresdb

  app_dev:
    build:
      context: backend/app
      dockerfile: backend/app/Dockerfile.dev
    container_name: app_dev
    ports:
      - 8003:8080
    restart: on-failure
    volumes:
      - .:backend/app
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: "apartments"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - ./backend/pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pds@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile

  nginx:
    container_name: nginx
    build:
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/home/static
    ports:
      - 81:81
      - 82:82
    depends_on:
      - app_prod1
      - app_prod2
      - app_prod3
      - app_dev

volumes:
  pg_data:
  static_volume:
  pgadmin-data:
