version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: backend/app/Dockerfile.dev
    container_name: renter_app_dev
    ports:
      - 8003:8080
    restart: on-failure
    volumes:
      - .:backend/app
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    container_name: renter_postgres_dev
    environment:
      POSTGRES_DB: "apartments"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - ./backend/pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: renter_pgadmin4_dev
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pds@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  frontend:
    container_name: renter_frontend_dev
    build:
      context: .
      dockerfile: ./frontend/Dockerfile

  nginx:
    container_name: renter_nginx_dev
    build:
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/home/static
    ports:
      - 81:81
      - 82:82
    depends_on:
      - app_prod1
      - app_prod2
      - app_prod3
      - app_dev

volumes:
  pg_data:
  static_volume:
  pgadmin-data: