FROM golang:1.19.3-alpine3.15

RUN apk update && apk add --no-cache git && apk add --no-cach bash && apk add build-base

RUN mkdir /app
WORKDIR /app

COPY . .

RUN go mod init

RUN go install -v

RUN go build -o /build

CMD [ "/build" ]